import Advertisement from '@/components/organism/advertisement/Advertisement'
import PostOverlayCard from '@/components/molecules/card/PostOverlayCard'
import PostCard from '@/components/molecules/card/PostCard'
import PageInfo from '@/components/organism/pageInfo/PageInfo'
import React, { Suspense } from 'react'
import { Post } from '@/models/post'
import { getClient } from '@/utils/client'
import { GET_POSTS, getPostsByCategory } from '@/utils/actions'
import NotFoundPage from '@/app/not-found'
import Loading from '@/app/loading'

export const metadata = {
   title: 'Blog Page | MetaBlog',
   description: 'Generated by create next app',
}

export const dynamicParams = true;

interface Props {
   params: { slug: string }
}

const PostsByCategory = async ({ params }: Props) => {

   const posts = await getPostsByCategory(params.slug, 120);
   //const haveMorePosts = Boolean(data?.posts?.pageInfo?.hasNextPage);
   if (posts.posts.nodes.length === 0) return (
      <NotFoundPage />
   )
   return (
      <Suspense fallback={<Loading />}>

         <main>
            <div className="container mx-auto  p-3">
               {/* Page title info */}
               <section>
                  <PageInfo pageTitle={posts.name} breadcrumbs={[{ text: posts.name, url: "/blog" }]} />
               </section>

               {/* Banner */}
               <section className="my-12">
                  <PostOverlayCard post={posts.posts.nodes[0]} />
               </section>

               {/* All posts component */}
               <section className="my-20">
                  <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                     {posts.posts.nodes.map((item: Post) => (
                        <PostCard key={item.title} post={item} />
                     ))}
                  </div>

               </section>

               {/* Advertisement component 
               <section className="mb-24">
                  <Advertisement />
               </section>*/}
            </div>
         </main>
      </Suspense>
   )
}

export default PostsByCategory
