import AuthorInfo from '@/components/organism/authorInfo/AuthorInfo'
import PostCard from '@/components/molecules/card/PostCard'
import React from 'react'
import { getPosts } from '@/utils/actions'

export const metadata = {
   title: 'Author Page | MetaBlog',
   description: 'Generated by create next app',
}

const Author = async () => {
   const posts = await getPosts(1);
   return (
      <main>
         {/* Author info */}
         <section>
            <AuthorInfo />
         </section>

         {/* Latest Post */}
         <section>
            <div className="container mx-auto mt-12 mb-24 px-5 sm:px-0">
               <h3 className="text-base-content font-bold text-2xl mb-8">
                  Latest Post
               </h3>
               <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                  {posts.map(
                     (item: any, index: number) => (
                        <div key={index}>
                           <PostCard post={item} />
                        </div>
                     )
                  )}
               </div>
            </div>
         </section>
      </main>
   )
}

export default Author
